---
- hosts: rocky 
  user: sysadmin
  become: true

  tasks:

  - name: Tener instalado el servidor apache 
    ansible.builtin.yum:
      name: httpd
      state: present
  
  - name: Apache inicio y habilitado
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

  - name: Habilitar puertos 80 y 443 
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true

    loop: 
    - http
    - https  
  
  - name: Instalar index.html costunizado con un tamplate
    ansible.builtin.template:
      src: ./templates/indesx.j2
      dest: /var/www/html/index.html
      mode: '0444'
      owner: apache
      group: apache
      

      


      

      

  
